-- Phase 2 data import: BOSBA Premium Foods real catalog from AppSheet export.
-- Replaces the Phase 0 placeholder products/categories for this brand.
-- Curated: excludes admin-only categories (Wishlist/Package/New Demand/Grab/
-- Overstock/Pre-Order/Product Type B&C/blank) and rows with no price --
-- see the skip lists reported alongside this migration for follow-up.

delete from products
where brand_id = (select id from brands where slug = 'bosba-premium-foods');

delete from categories
where brand_id = (select id from brands where slug = 'bosba-premium-foods');

with brand as (
  select id from brands where slug = 'bosba-premium-foods'
)
insert into categories (brand_id, name, sort_order)
select (select id from brand), v.name, v.sort_order
from (values
  ('Plum Wine & Liqueur', 0),
  ('Sparkling Wine', 1),
  ('Beverage', 2),
  ('Dried Items', 3),
  ('Dressing & Mayonnaise', 4),
  ('Miso', 5),
  ('Sauce & Oil', 6),
  ('Soup', 7),
  ('Sweet Cooking Rice Wine', 8),
  ('Meat & Poultry', 9),
  ('Processed Foods', 10),
  ('Rice & Flour', 11),
  ('Fresh Premium', 12),
  ('Fish', 13),
  ('Fish Roe', 14),
  ('Octopus', 15),
  ('Shell', 16),
  ('Shrimp', 17),
  ('Squid', 18),
  ('Frozen Premium', 19),
  ('Vegetables', 20),
  ('ឈុតត្រីនិស៊ីន', 21),
  ('ឈុតគ្រឿងបន្ថែម', 22),
  ('ឈុតត្រីខាត់ស្សុអុ', 23),
  ('ឈុតត្រីសាលម៉ុន', 24),
  ('Caviar', 25),
  ('Ingredient', 26),
  ('Dessert', 27),
  ('Uni - Fresh Urchin', 28),
  ('Fruits', 29),
  ('Tuna', 30),
  ('Beer', 31),
  ('Sake', 32),
  ('Future Fish', 33),
  ('Sashimi Set', 34),
  ('Tuna Sashimi Set', 35),
  ('ឈុតអូម៉ាកាសិ', 36),
  ('Sushi Set', 37),
  ('Japanese Sake', 38),
  ('Engawa Ikura Gunkan Sushi', 39),
  ('Sake Promotion', 40),
  ('Health Supplement', 41),
  ('Japanese Whisky', 42),
  ('Soft Drink', 43),
  ('Kampot Pepper', 44),
  ('Japanese Spirit', 45),
  ('Soy Sauce', 46)
) as v(name, sort_order);

with brand as (
  select id from brands where slug = 'bosba-premium-foods'
),
cat_map as (
  select id, name from categories where brand_id = (select id from brand)
)
insert into products (brand_id, category_id, sku, name, price, unit, is_active)
select (select id from brand), cat_map.id, v.sku, v.name, v.price, v.unit, true
from (values
  ('KU001a', 'Frozen Kaki Oyster 2L', 27.00, 'កញ្ចប់', 'Shell'),
  ('EJ089a', 'Frozen Kaki Oyster L', 24.00, 'កញ្ចប់', 'Shell'),
  ('TB090b', 'Frozen Japanese Wheat Noodle 200g', 5.50, 'កញ្ចប់', 'Processed Foods'),
  ('TB090a', 'Frozen Japanese Wheat Noodle 250g', 6.00, 'កញ្ចប់', 'Processed Foods'),
  ('AZ020a', 'Frozen Octopus With Wasabi 1kg', 34.00, 'គីឡូ', 'Processed Foods'),
  (NULL, 'Frozen Octopus With Wasabi 500g', 17.00, 'ប្រអប់', 'Processed Foods'),
  (NULL, 'Frozen Octopus With Wasabi 250g', 9.00, 'ប្រអប់', 'Processed Foods'),
  ('AZ085a', 'Herring With Red Fish Roe 1Kg', 35.00, 'គីឡូ', 'Fish Roe'),
  ('AZ085b', 'Herring With Red Fish Roe 1Pc', 5.50, 'ដុំ', 'Fish Roe'),
  ('AZ045a', 'Herring With Yelllow Fish Roe 1Kg', 35.00, 'គីឡូ', 'Fish Roe'),
  ('AZ045b', 'Herring With Yelllow Fish Roe 1Pc', 5.50, 'ដុំ', 'Fish Roe'),
  ('FC048a', 'Frozen Boiled Octopus 1-1.5kg', 35.00, 'គីឡូ', 'Octopus'),
  ('SKY087b', 'Frozen Grilled Eel Fillet 220g', 15.00, 'កញ្ចប់', 'Fish'),
  ('SKY072b', 'Frozen Grilled Eel Fillet 340g', 23.00, 'កញ្ចប់', 'Fish'),
  ('FC030a', 'Frozen Edamame Beans 500g', 3.20, 'កញ្ចប់', 'Processed Foods'),
  ('FC030b', 'Frozen Edamame Beans 1kg', 6.20, 'កញ្ចប់', 'Processed Foods'),
  ('FC002a1', 'Frozen Sweet Shrimp 3L', 15.50, 'កញ្ចប់', 'Shrimp'),
  ('MMR001a', 'Frozen Young Yellowtail Fillet - 1Kg', 55.00, 'គីឡូ', 'Fish'),
  ('FJ0039a', 'Hokkigai Surl Clam', 47.00, 'កញ្ចប់', 'Shell'),
  ('OF001a', 'Frozen White Leg Shrimp 4L', 9.00, 'កញ្ចប់', 'Shrimp'),
  ('MF007a', 'Frozen Imitation Crab Meat', 6.50, 'កញ្ចប់', 'Processed Foods'),
  ('MY001a', 'Frozen Mackerel Fillet', 6.60, 'កញ្ចប់', 'Fish'),
  ('MSR037a', 'Frozen Salmon Roe 500g', 90.00, 'ប្រអប់', 'Fish Roe'),
  ('SH029a', 'Frozen Mackerel', 8.00, 'គីឡូ', 'Fish'),
  ('MMR088a', 'Frozen No Shell Scallop 1kg', 70.00, 'កញ្ចប់', 'Shell'),
  ('FC033a', 'Frozen Bigfin Reef Squid Slice', 6.50, 'កញ្ចប់', 'Squid'),
  ('FC049a', 'Frozen Chinese Seaweed', 6.70, 'កញ្ចប់', 'Processed Foods'),
  ('FC042a', 'Frozen Soft Shell Crab', 22.50, 'កញ្ចប់', 'Shell'),
  ('SF170', 'Frozen Pork Gyoza', 15.00, 'កញ្ចប់', 'Processed Foods'),
  ('RV049a', 'Dried Sea Grapes 1box', 9.00, 'ប្រអប់', 'Processed Foods'),
  ('RV049b', 'Dried Sea Grapes 1pkt', 1.00, 'កញ្ចប់', 'Processed Foods'),
  ('JH001b', 'Roasted Sushi Seaweed - 25Pcs', 1.00, 'កញ្ចប់', 'Dried Items'),
  ('YA005a', 'Frozen Lean Bluefin Tuna - G', 120.00, 'គីឡូ', 'Tuna'),
  ('YA005b', 'Frozen Medium Bluefin Tuna - G', 145.00, 'គីឡូ', 'Tuna'),
  ('MSR081a', 'Frozen Red King Crab Leg', 125.00, 'កញ្ចប់', 'Shell'),
  ('NR245c', 'Boiled Monkfish Liver', 22.00, 'កញ្ចប់', 'Fish'),
  ('MY013a', 'Frozen Seared Bonito - 100g', 50.00, 'គីឡូ', 'Fish'),
  ('BU089b', 'Hibiki Blender''s Choice', 290.00, 'ដប', 'Japanese Whisky'),
  ('BU072a', 'The Yamazaki Single Malt', 185.00, 'ដប', 'Japanese Whisky'),
  ('BU057a', 'The Yamazaki 12 Years', 310.00, 'ដប', 'Japanese Whisky'),
  ('BU088a', 'The Hakushu Single Malt', 150.00, 'ដប', 'Japanese Whisky'),
  ('BU142a', 'Sparkling Jelly Apple', 2.90, 'កំប៉ុង', 'Sparkling Wine'),
  ('BU142b', 'Sparkling Jelly Peach', 2.90, 'កំប៉ុង', 'Sparkling Wine'),
  ('BU142c', 'Sparkling Jelly ​​Plum', 2.90, 'កំប៉ុង', 'Sparkling Wine'),
  (NULL, 'Dried Black Kampot Pepper 25g', 4.20, 'កញ្ចប់', 'Kampot Pepper'),
  (NULL, 'Dried Red Kampot Pepper 25g', 6.60, 'កញ្ចប់', 'Kampot Pepper'),
  (NULL, 'Dried White Kampot Pepper 25g', 6.60, 'កញ្ចប់', 'Kampot Pepper'),
  (NULL, 'Dried Black Kampot Pepper 50g', 6.00, 'កញ្ចប់', 'Kampot Pepper'),
  (NULL, 'Dried Red Kampot Pepper 50g', 10.80, 'កញ្ចប់', 'Kampot Pepper'),
  (NULL, 'Dried White Kampot Pepper 50g', 10.80, 'កញ្ចប់', 'Kampot Pepper'),
  (NULL, 'Salted Black Fresh Kampot Pepper 40g', 6.60, 'កញ្ចប់', 'Kampot Pepper'),
  (NULL, 'Salted Green Fresh Kampot Pepper 40g', 6.60, 'pkt', 'Kampot Pepper'),
  ('TF001a', 'Nori Seaweed L', 4.00, 'កញ្ចប់', 'Dried Items'),
  (NULL, 'Oba', 1.50, 'កញ្ចប់', 'Vegetables'),
  ('CM0164', 'Shoyu Soy Sauce 5L', 17.80, 'ដប', 'Ingredient'),
  (NULL, 'Bafun Narabi (High Grade) 250g', 165.00, '250g', 'Uni - Fresh Urchin'),
  (NULL, 'Ogawa Narabi (High Grade) 250g', 175.00, 'ប្រអប់', 'Uni - Fresh Urchin'),
  (NULL, 'Bafun Bara (Normal Grade) 250g', 140.00, '250g', 'Uni - Fresh Urchin'),
  (NULL, 'Unagi Bones 26g', 2.90, 'ក្រាម', 'Dried Items'),
  ('JH001a', 'Roasted Sushi Seaweed - 100Pcs', 15.00, 'ដុំ', 'Dried Items'),
  ('CM0180', 'Frozen Whitebait', 18.50, 'កញ្ចប់', 'Fish'),
  ('MY008a', 'Frozen Dried Young Sardines', 4.50, 'កញ្ចប់', 'Processed Foods'),
  ('MY005a', 'Frozen Capelins 3L', 3.20, 'កញ្ចប់', 'Fish'),
  ('MK034a', 'Frozen Narutomaki', 3.00, 'កញ្ចប់', 'Processed Foods'),
  ('TI082a', 'Pink Sliced Ginger Pickle', 8.00, 'កញ្ចប់', 'Processed Foods'),
  ('TI082b', 'White Sliced Ginger Pickle', 8.00, 'កញ្ចប់', 'Processed Foods'),
  ('BU013a', 'Iichiko Silhouette', 20.50, 'ដប', 'Japanese Spirit'),
  ('BU044a', 'Black Sugar Plum Wine', 25.00, 'ដប', 'Plum Wine & Liqueur'),
  ('FC072a', 'Arabiki Pork Sausage', 10.80, 'កញ្ចប់', 'Processed Foods'),
  ('NR216a', 'Frozen Tsubugai Slice', 25.00, 'កញ្ចប់', 'Shell'),
  ('FC004a', 'Frozen Sillago Fillet', 14.30, 'កញ្ចប់', 'Fish'),
  ('BU073a', 'The Hakusu Whisky 18 Years', 1200.00, 'ដប', 'Japanese Whisky'),
  ('BU075a', 'Nikka Whisky Taketsuru Pure Malt', 80.00, 'ដប', 'Japanese Whisky'),
  ('MK016', 'Kewpie Mayonnaise', 9.50, 'កំប៉ុង', 'Dressing & Mayonnaise'),
  ('EN002a', 'Nisshin Tempura Flour', 3.90, 'កញ្ចប់', 'Rice & Flour'),
  ('CM0134', 'Takoyaki Flour', 8.30, 'កញ្ចប់', 'Rice & Flour'),
  ('BU041a', 'Suntory Shimasenka Plum Wine', 20.50, 'ដប', 'Plum Wine & Liqueur'),
  ('EN095a', 'Shibaduke', 4.50, 'កញ្ចប់', 'Processed Foods'),
  ('BU040a', 'Choya Kishu Plum Wine', 24.50, 'ដប', 'Plum Wine & Liqueur'),
  ('BU043a', 'Plum Wine With Green Tea', 22.00, 'ដប', 'Plum Wine & Liqueur'),
  ('BU077a', 'Shochu Unkai Kuromaru', 25.00, 'ដប', 'Japanese Spirit'),
  ('BU039a', 'Plum Wine With Honey', 19.60, 'ដប', 'Plum Wine & Liqueur'),
  ('BU015a', 'Kannokou Shochu Mugi', 27.00, 'ដប', 'Plum Wine & Liqueur'),
  ('BU017a', 'Hakutake Shiro', 25.00, 'ដប', 'Plum Wine & Liqueur'),
  ('BU004a', 'Kuro Kirishima Shochu Imo', 19.60, 'ដប', 'Japanese Spirit'),
  ('EN040a', 'Spoon Sugar Johakuto', 4.70, 'កញ្ចប់', 'Ingredient'),
  ('EN033a', 'Dashi Pack', 28.00, 'កញ្ចប់', 'Ingredient'),
  ('EN039a', 'Refined Salt', 2.80, 'កញ្ចប់', 'Ingredient'),
  ('KA027a', 'Kaneku Nama Wasabi', 19.50, 'កញ្ចប់', 'Processed Foods'),
  ('FC051a', 'Shaki Shaki Wasabi', 14.50, 'កញ្ចប់', 'Processed Foods'),
  ('CM0008', 'Frozen Minced Tuna 250g', 12.70, 'កញ្ចប់', 'Tuna'),
  ('FC047a', 'Frozen Ark Shell', 32.50, 'កញ្ចប់', 'Shell'),
  ('BU074a', 'Hibiki Whisky 21 Years', 1550.00, 'ដប', 'Japanese Whisky'),
  ('MSR079a', 'Frozen Flounder Fin', 36.00, 'កញ្ចប់', 'Fish'),
  ('MSR084a', 'Fresh Seaweed', 7.30, 'កញ្ចប់', 'Processed Foods'),
  ('CM0133', 'Karaage Flour', 8.50, 'កញ្ចប់', 'Rice & Flour'),
  ('EN003a', 'JFDA Tempura Flour', 6.60, 'កញ្ចប់', 'Rice & Flour'),
  ('EN004a', 'NAKAO Katakuri Flour', 6.80, 'កញ្ចប់', 'Rice & Flour'),
  ('NR214c', 'Frozen Crab Butter Can', 20.00, 'កំប៉ុង', 'Fish'),
  ('SKY080a', 'Frozen Sea Eel Simmered', 25.00, 'កញ្ចប់', 'Fish'),
  ('MK010a', 'Frozen Boiled Fish Paste', 2.70, 'Pc', 'Processed Foods'),
  ('JFP0025a', 'Green Butter Head Lettuce', 3.20, 'កញ្ចប់', 'Vegetables'),
  ('JFP0028a', 'Romaine Lettuce', 3.20, 'កញ្ចប់', 'Vegetables'),
  ('JFP0024a', 'Iceberg Lettuce', 3.20, 'កញ្ចប់', 'Vegetables'),
  ('JFP0026a', 'Green Batavia Lettuce', 3.20, 'កញ្ចប់', 'Vegetables'),
  ('JFP0023a', 'Red Oak Leaf Lettuce', 3.20, 'កញ្ចប់', 'Vegetables'),
  ('JFP0048a', 'Frisee', 3.20, 'កញ្ចប់', 'Vegetables'),
  ('JFP0033a', 'Lollo Rossa Lettuce', 3.20, 'កញ្ចប់', 'Vegetables'),
  ('JFP0044a', 'Mixed Lettuce', 3.20, 'កញ្ចប់', 'Vegetables'),
  ('JFP0052b', 'Japanese Bitter Gourd', 2.50, 'កញ្ចប់', 'Vegetables'),
  ('JFP0030b', 'Mini Eggplant', 1.30, 'កញ្ចប់', 'Vegetables'),
  ('JFP0001b', 'Japanese Okra', 1.10, 'កញ្ចប់', 'Vegetables'),
  ('JFP0031b', 'Sweet Green Chilli', 1.20, 'កញ្ចប់', 'Vegetables'),
  ('JFP0042b', 'Oyster Mushroom', 1.70, 'កញ្ចប់', 'Vegetables'),
  ('JFP0038b', 'Cherry Tomato', 1.20, 'កញ្ចប់', 'Vegetables'),
  ('BU142d', 'Sparkling Jelly Lemon', 2.90, 'កំប៉ុង', 'Sparkling Wine'),
  ('BU142e', 'Sparkling Jelly Mango', 2.90, 'កំប៉ុង', 'Sparkling Wine'),
  ('FC021c', 'Frozen Vinegared Mackerel', 4.40, 'កញ្ចប់', 'Fish'),
  ('BU042a', 'Tantakatan Plum Wine', 22.00, 'ដប', 'Plum Wine & Liqueur'),
  ('BU018a', 'Tantakatan Shochu Shiso', 18.70, 'ដប', 'Japanese Spirit'),
  ('EN020a', 'Mizkan Vinegar Meisen', 13.20, 'ដប', 'Ingredient'),
  ('TI155a', 'Frozen Mentaiko Paste', 25.00, 'កញ្ចប់', 'Fish Roe'),
  ('FC013a', 'Frozen Mixed Seafoods', 14.50, 'កញ្ចប់', 'Fish'),
  ('AZ084a', 'Shishamo Fish Roe', 20.00, 'កញ្ចប់', 'Fish Roe'),
  ('BIF049b', 'Frozen Sesame Seaweed Salad', 9.60, 'កញ្ចប់', 'Processed Foods'),
  ('MF009d', 'Frozen Black Tiger Shrimp', 13.20, 'កញ្ចប់', 'Shrimp'),
  ('MY116a', 'Hikari Miso Dashi', 6.80, 'កញ្ចប់', 'Miso'),
  ('CM0093', 'Salted Japanese Plum', 8.40, 'កញ្ចប់', 'Processed Foods'),
  ('CM0103b', 'Japanese BBQ Sauce', 9.90, 'កញ្ចប់', 'Sauce & Oil'),
  ('CM0044b', 'Tonkatsu Sauce', 8.70, 'ដប', 'Sauce & Oil'),
  ('CM0187', 'Japanese Plum Paste', 5.10, 'កញ្ចប់', 'Sauce & Oil'),
  ('TW098a', 'Yomeishu Peach', 8.70, 'ដប', 'Plum Wine & Liqueur'),
  ('NF005a', 'Nakata Apple And Prune Liquor', 15.00, 'ដប', 'Plum Wine & Liqueur'),
  ('NF004a', 'Nakata Peach And Prune Liquor', 15.00, 'ដប', 'Plum Wine & Liqueur'),
  ('EN141a', 'ITO EN Oi Ocha Premium Tea bag', 10.50, 'ប្រអប់', 'Beverage'),
  ('TW101b', 'ITO EN Oi Ocha Sarasara Bitter Green Tea', 10.50, 'ប្រអប់', 'Beverage'),
  ('FC016a', 'Frozen Shrimp Roe', 21.00, 'ប្រអប់', 'Fish Roe'),
  ('LH055a', 'Flying Fish Roe', 40.00, 'កញ្ចប់', 'Fish Roe'),
  ('EN024a', 'Hon Mirin', 18.00, 'ដប', 'Sweet Cooking Rice Wine'),
  ('EN118a', 'Cooking Sake', 12.00, 'ដប', 'Sweet Cooking Rice Wine'),
  ('KU001c', 'Frozen Oysters With Shell', 35.00, 'កញ្ចប់', 'Shell'),
  ('MY137a', 'Sesame Soysauce Dressing', 13.40, 'កំប៉ុង', 'Dressing & Mayonnaise'),
  ('MY070a', 'Dried Seaweed For Soup', 34.80, 'ដប', 'Soup'),
  ('SF117', 'Dried Bread Crumbs', 7.20, 'កញ្ចប់', 'Rice & Flour'),
  ('EN018a', 'Citrus Seasoned Soy Sauce', 18.00, 'ដប', 'Soy Sauce'),
  ('CM0159', 'Inari Tofu Pockets', 5.40, 'កញ្ចប់', 'Processed Foods'),
  ('MY189a', 'Baked Fish Cake', 3.40, 'កញ្ចប់', 'Processed Foods'),
  ('CM0088', 'Frozen Salted Seaweed', 11.00, 'កញ្ចប់', 'Processed Foods'),
  ('CM0167', 'Fish Paste', 10.10, 'កញ្ចប់', 'Processed Foods'),
  ('MY050a', 'Gyoza Skins', 3.00, 'កញ្ចប់', 'Processed Foods'),
  ('MY086a', 'Salted Squid', 38.00, 'កញ្ចប់', 'Squid'),
  ('LH096a', 'Kewpie Sweet Mayonnaise', 8.20, 'កំប៉ុង', 'Dressing & Mayonnaise'),
  ('CM0154', 'Bigfin Reef Squid', 27.60, 'គីឡូ', 'Squid'),
  ('FJ171a', 'Frozen Chicken Gyoza', 10.80, 'កញ្ចប់', 'Processed Foods'),
  ('MSR037c', 'Frozen Salmon Roe 100g', 18.00, 'ប្រអប់', 'Fish Roe'),
  ('MSR037d', 'Frozen Salmon Roe 50g', 9.50, 'ប្រអប់', 'Fish Roe'),
  ('MSR037e', 'Frozen Salmon Roe 25g', 8.00, 'ប្រអប់', 'Fish Roe'),
  ('NR177e', 'Frozen Sweet Shrimp 2.5L HOSO', 78.00, 'កញ្ចប់', 'Shrimp'),
  ('MF046a', 'Frozen whiteleg shrimp for Sushi 6L', 14.40, 'កញ្ចប់', 'Shrimp'),
  ('MF009e', 'Frozen whiteleg shrimp 26/30', 11.80, 'កញ្ចប់', 'Shrimp'),
  ('NR222c', 'Frozen Botanebi', 105.60, 'កញ្ចប់', 'Shrimp'),
  ('NR464a', 'Frozen Akaebi', 105.00, 'ប្រអប់', 'Shrimp'),
  ('MY058a', 'Frozen Fried Shrimp', 6.50, 'កញ្ចប់', 'Shrimp'),
  ('FC425a', 'Frozen Octopus Slice 7-8 g/pc', 9.80, 'កញ្ចប់', 'Octopus'),
  ('FC028a', 'Frozen Squid Pineapple for cook', 7.00, 'គីឡូ', 'Squid'),
  ('MY106a', 'Frozen Kaki (Oyster) Fry', 13.80, 'កញ្ចប់', 'Shell'),
  ('FC029a', 'Frozen greenlip half mussel "M"', 14.40, 'កញ្ចប់', 'Shell'),
  ('FC173a', 'Frozen Sea-Urchin/ Uni', 33.80, 'កញ្ចប់', 'Shell'),
  ('FC059b', 'Frozen Asari', 11.00, 'កញ្ចប់', 'Shell'),
  ('FC391a', 'Frozen Shijimi', 13.50, 'កញ្ចប់', 'Shell'),
  ('MY232a', 'Frozen Hamagur', 7.50, 'កញ្ចប់', 'Shell'),
  ('NR082c', 'Frozen Mentaiko/ Spicy Cod Roe', 85.00, 'កញ្ចប់', 'Fish Roe'),
  ('TI045a', 'Frozen herring roe/ Kazunoko', 8.40, 'កញ្ចប់', 'Fish Roe'),
  ('MY245a', 'Frozen Monkfish Liver', 22.00, 'កញ្ចប់', 'Fish'),
  ('MY029a', 'Frozen dried gourd shavings/Kanpyo', 10.20, 'កញ្ចប់', 'Processed Foods'),
  ('MY031b', 'Frozen yellow pickled radish/Takuan', 8.40, 'កញ្ចប់', 'Processed Foods'),
  ('MY032a', 'Frozen fried egg', 12.60, 'កញ្ចប់', 'Processed Foods'),
  ('KA089a', 'Frozen citron peel/Yuzu kawa', 15.60, 'កញ្ចប់', 'Processed Foods'),
  ('NR024a', 'Frozen marinated firefly squid', 72.00, 'កញ្ចប់', 'Processed Foods'),
  ('CM0082', 'Frozen scallop with kimuchi sauce', 13.50, 'កញ្ចប់', 'Processed Foods'),
  ('CM0200', 'Frozen Chinese jellyfish', 14.40, 'កញ្ចប់', 'Processed Foods'),
  ('NR176a', 'Vinegared mozuku seaweed(chilled)', 72.00, 'កញ្ចប់', 'Processed Foods'),
  ('MY044a', 'Frozen grated yam/ Tororo', 16.80, 'កញ្ចប់', 'Processed Foods'),
  ('MY045a', 'Fried bean curd (Chilled)', 17.40, 'កញ្ចប់', 'Processed Foods'),
  ('BIF0085a', 'Frozen fresh wasabi powder', 19.50, 'កញ្ចប់', 'Processed Foods'),
  ('MY030a', 'Mini wasabi pack', 5.60, 'កញ្ចប់', 'Processed Foods'),
  ('MY035a', 'Mini soysauce pack', 11.60, 'កញ្ចប់', 'Processed Foods'),
  ('MY377a', 'Sakura denbu', 7.20, 'កញ្ចប់', 'Processed Foods'),
  ('MY094a', 'Frozen dried shrimp/Hoshi ebi', 3.20, 'កញ្ចប់', 'Processed Foods'),
  ('NR067b', 'Frozen Shirauo', 50.40, 'កញ្ចប់', 'Processed Foods'),
  ('SF170b', 'Frozen Pork Gyoza (S pack)', 7.50, 'កញ្ចប់', 'Processed Foods'),
  ('MK103a', 'Frozen bread crumbs/ Panko', 16.80, 'កញ្ចប់', 'Rice & Flour'),
  ('CM0132', 'Tempra powder', 6.80, 'កញ្ចប់', 'Rice & Flour'),
  ('MY109a', 'NIPPN Tempra powder', 5.90, 'កញ្ចប់', 'Rice & Flour'),
  ('MY116b', 'Hikari miso aka', 6.80, 'កញ្ចប់', 'Miso'),
  ('MY117a', 'Matsushiro miso', 6.80, 'កញ្ចប់', 'Miso'),
  ('MY116c', 'Hikari awase miso', 8.60, 'កញ្ចប់', 'Miso'),
  ('CM0193a', 'Shoyu grade A 1.5L / Soysauce', 6.80, 'ដប', 'Soy Sauce'),
  ('MY052a', 'Leaf of magnolia/ Houba', 10.80, 'កញ្ចប់', 'Sweet Cooking Rice Wine'),
  ('EN124a', 'Bamboo leaf/ Sasanoha', 11.90, 'កញ្ចប់', 'Sweet Cooking Rice Wine'),
  ('CM0195a', 'Sweet cooking rice wien 2L', 16.80, 'ដប', 'Sweet Cooking Rice Wine'),
  ('CM0225a', 'Sweet cooking rice wien 5L', 39.60, 'ដប', 'Sweet Cooking Rice Wine'),
  ('CM0195b', 'Cooking rice wine 2L', 16.80, 'ដប', 'Sweet Cooking Rice Wine'),
  ('CM0225b', 'Cooking rice wine 5L', 39.60, 'ដប', 'Sweet Cooking Rice Wine'),
  ('SF033a', 'Dashinomono (Hondashi)', 20.00, 'កញ្ចប់', 'Soup'),
  ('CM0165', 'Bonito Concentred Soup', 36.50, 'ដប', 'Soup'),
  ('CM0166', 'Seaweed Concentred Soup', 10.00, 'ដប', 'Soup'),
  ('CM0220', 'Ponzu sauce 1L', 6.30, 'ដប', 'Soup'),
  ('MY135a', 'Sanbishi tsuyu', 11.00, 'ដប', 'Soup'),
  ('CM0041', 'Worcester(USUTER) sauce', 7.20, 'ដប', 'Sauce & Oil'),
  (NULL, 'Teriyaki sauce', 3.40, 'ដប', 'Sauce & Oil'),
  ('CM0192', 'YAKISOBA SAUCE', 8.90, 'ដប', 'Sauce & Oil'),
  ('MY136a', 'QP baisen sesami dlessing', 15.80, 'កំប៉ុង', 'Dressing & Mayonnaise'),
  ('MY113a', 'QP caeser dreasing', 9.40, 'កំប៉ុង', 'Dressing & Mayonnaise'),
  ('MY095a', 'Fukujinzuke', 12.00, 'កញ្ចប់', 'Dried Items'),
  ('MY084a', 'Sushi nori gold no cut', 50.60, 'កញ្ចប់', 'Dried Items'),
  ('MY084b', 'Sushi nori gold half cut', 50.60, 'កញ្ចប់', 'Dried Items'),
  ('MY033a', 'Economy nori no cut', 26.80, 'កញ្ចប់', 'Dried Items'),
  ('MY034a', 'Economy nori half cut', 27.00, 'កញ្ចប់', 'Dried Items'),
  ('MY093a', 'Kizami nori', 18.60, 'កញ្ចប់', 'Dried Items'),
  ('CM0122', 'Maguro thread cut (Ito kezuri)', 2.90, 'កញ្ចប់', 'Dried Items'),
  ('CM0124', 'Bonito powder', 52.00, 'កញ្ចប់', 'Dried Items'),
  ('MY049a', 'Dry Kanpyo', 15.80, 'កញ្ចប់', 'Dried Items'),
  ('SF035a', 'Dried bonito flakes', 25.00, 'កញ្ចប់', 'Dried Items'),
  ('NR137a', 'Frozen Black Cod Fillet', 78.00, 'pcs', 'Fish'),
  ('MY120a', 'Frozen Salted Mackerel Fillet', 9.00, 'pcs', 'Fish'),
  ('UT010a', 'Frozen Sardine Fillet', 10.10, 'pcs', 'Fish'),
  ('FC058a', 'Frozen Atka Mackerel', 7.70, 'pcs', 'Fish'),
  ('MK019a', 'Frozen Capelins', 3.20, 'កញ្ចប់', 'Fish'),
  ('MK048a', 'Chopstick', 3.40, 'កញ្ចប់', 'Dried Items'),
  ('CM0140', 'Yukari chacoal', 6.60, 'គីឡូ', 'Dried Items'),
  ('MY115a', 'Teppo kushi 18cm', 7.30, 'កញ្ចប់', 'Dried Items'),
  ('MY115b', 'Teppo kushi 9cm', 9.60, 'កញ្ចប់', 'Dried Items'),
  ('TMR141a', 'Wagyu Sirloin/Striploin (A4)', 140.00, 'គីឡូ', 'Meat & Poultry'),
  ('TM169a', 'Wagyu Tenderloin (A4)', 205.00, 'គីឡូ', 'Meat & Poultry'),
  ('TMR150a', 'Wagyu Kobe Wine Beef Chuck Rib(A4)', 115.00, 'គីឡូ', 'Meat & Poultry'),
  ('MY046a', 'Beef Tongue', 26.40, 'គីឡូ', 'Meat & Poultry'),
  ('CM0067', 'Beef Tongue (Thai high end beef', 30.00, 'គីឡូ', 'Meat & Poultry'),
  ('BU006a', 'Akakirishima Shochu Imo', 35.00, 'ដប', 'Plum Wine & Liqueur'),
  ('BU080a', 'Akane Kirishma', 48.70, 'ដប', 'Japanese Spirit'),
  ('BU011a', 'Satsuma Kuroshiranami', 25.00, 'ដប', 'Plum Wine & Liqueur'),
  (NULL, 'B01: Nishin Tuna Ikura', 19.50, 'ឈុត', 'ឈុតត្រីនិស៊ីន'),
  (NULL, 'B02: Nishin Ikura', 14.00, 'ឈុត', 'ឈុតត្រីនិស៊ីន'),
  ('JFP0057a', 'V01', 0.50, 'ឈុត', 'ឈុតគ្រឿងបន្ថែម'),
  (NULL, 'B03: Katsuo Tuna Ikura', 19.50, 'ឈុត', 'ឈុតត្រីខាត់ស្សុអុ'),
  (NULL, 'B04: Katsuo Ikura', 15.70, 'ឈុត', 'ឈុតត្រីខាត់ស្សុអុ'),
  (NULL, 'B05: Salmon Yellow Nishin S', 11.90, 'ឈុត', 'ឈុតត្រីសាលម៉ុន'),
  (NULL, 'B06: Salmon Yellow Nishin L', 25.00, 'ឈុត', 'ឈុតត្រីសាលម៉ុន'),
  (NULL, 'B07: Salmon S', 11.90, 'ឈុត', 'ឈុតត្រីសាលម៉ុន'),
  (NULL, 'B08: Salmon L', 20.00, 'ឈុត', 'ឈុតត្រីសាលម៉ុន'),
  (NULL, 'B09: Salmon Red Nishin S', 11.90, 'ឈុត', 'ឈុតត្រីសាលម៉ុន'),
  (NULL, 'B10: Salmon Red Nishin L', 21.00, 'ឈុត', 'ឈុតត្រីសាលម៉ុន'),
  (NULL, 'B11: Yellow Nishin S', 11.00, 'ឈុត', 'ឈុតត្រីនិស៊ីន'),
  (NULL, 'B12: Yellow Nishin L', 20.50, 'ឈុត', 'ឈុតត្រីនិស៊ីន'),
  (NULL, 'B13: Red Nishin S', 11.00, 'ឈុត', 'ឈុតត្រីនិស៊ីន'),
  (NULL, 'B14: Red Nishin L', 20.50, 'ឈុត', 'ឈុតត្រីនិស៊ីន'),
  (NULL, 'B15: Salmon Yellow Red Nishin L', 30.00, 'ឈុត', 'ឈុតត្រីសាលម៉ុន'),
  ('HC001c', 'Fresh Salmon Fillet 100g', 40.00, 'គីឡូ', 'Fish'),
  (NULL, 'V02', 0.50, 'កញ្ចប់', 'ឈុតគ្រឿងបន្ថែម'),
  ('EN033b', 'Dashi Pack 3pkt', 4.50, 'កញ្ចប់', 'Ingredient'),
  (NULL, 'Hokkigai Surl Clam 100g', 5.00, 'កញ្ចប់', 'Shell'),
  (NULL, 'Frozen Boiled Octopus 100g', 3.90, 'ក្រាម', 'Octopus'),
  (NULL, 'Soy Sauce', 0.25, 'ប្រអប់', 'ឈុតគ្រឿងបន្ថែម'),
  (NULL, 'Wasabi', 0.25, 'ប្រអប់', 'ឈុតគ្រឿងបន្ថែម'),
  (NULL, 'Koh Kong Sauce', 0.50, 'ប្រអប់', 'ឈុតគ្រឿងបន្ថែម'),
  (NULL, 'Hokkigai Surl Clam 300g', 14.50, 'កញ្ចប់', 'Shell'),
  (NULL, 'Hokkigai Surl Clam 500g', 25.00, 'កញ្ចប់', 'Shell'),
  ('KNS088b', 'Frozen No Shell Scallop 500g', 40.00, 'កញ្ចប់', 'Shell'),
  ('KNS088c', 'Frozen No Shell Scallop 300g', 25.00, 'កញ្ចប់', 'Shell'),
  ('KNS088d', 'Frozen No Shell Scallop 100g', 8.00, 'កញ្ចប់', 'Shell'),
  (NULL, 'Frozen Oysters With Shell 500g', 16.50, 'កញ្ចប់', 'Shell'),
  (NULL, 'Salted Squid 500g', 20.00, 'កំប៉ុង', 'Squid'),
  (NULL, 'Fried Garlic', 1.00, 'ប្រអប់', 'ឈុតគ្រឿងបន្ថែម'),
  (NULL, 'White Ginger Pickle', 0.25, 'ប្រអប់', 'ឈុតគ្រឿងបន្ថែម'),
  ('TM141k', 'Wagyu Sirloin A5', 192.00, 'គីឡូ', 'Meat & Poultry'),
  (NULL, 'Wagyu Tenderloin A5', 225.00, 'pcs', 'Meat & Poultry'),
  ('UM004a', 'Strawberry Daifuku', 2.50, 'ដុំ', 'Dessert'),
  (NULL, 'Frozen Chinese Jelliyfish', 13.80, 'កញ្ចប់', 'Processed Foods'),
  ('MM597d', 'Frozen Uni', 27.00, 'ប្រអប់', 'Frozen Premium'),
  (NULL, 'Frozen Seasoned Flying Fish Roe', 30.70, 'កញ្ចប់', 'Fish Roe'),
  (NULL, 'Fresh Wasabi Size M', 35.00, 'ដុំ', 'Fresh Premium'),
  (NULL, 'Fresh Wasabi Size L', 55.00, 'ក្រាម', 'Fresh Premium'),
  ('UM004b', 'Strawberry Daifuku Gift set (6pc)', 19.00, 'ប្រអប់', 'Dessert'),
  (NULL, 'Frozen White Child - 500g', 50.40, 'កញ្ចប់', 'Fish'),
  (NULL, 'Fresh White Child', 95.00, 'កញ្ចប់', 'Fish'),
  ('EN033c', 'Dashi Pack 1pkt', 1.50, 'កញ្ចប់', 'Ingredient'),
  (NULL, 'Soft Cod - 500g', 68.00, 'ប្រអប់', 'Fresh Premium'),
  (NULL, 'Takeuchi Hanabako', 165.00, '250g', 'Uni - Fresh Urchin'),
  (NULL, 'Frozen Young Yellowtail Fillet - 100g', 6.00, 'ក្រាម', 'Fish'),
  ('MSR037b', 'Frozen Salmon Roe 250g', 45.00, 'ប្រអប់', 'Fish Roe'),
  ('JH001c', 'Roasted Sushi Seaweed - 20Pcs', 0.50, 'កញ្ចប់', 'Dried Items'),
  ('AZ084b', 'Shishamo Fish Roe-S', 0.90, 'កញ្ចប់', 'Fish Roe'),
  ('BIF049c', 'Frozen Sesame Seaweed Salad- S', 0.50, 'កញ្ចប់', 'Processed Foods'),
  ('BIF049d', 'Frozen Sesame Seaweed Salad-100g', 1.00, 'កញ្ចប់', 'Processed Foods'),
  ('CM0164b', 'Shoyu Soy Sauce 1L', 3.60, 'កំប៉ុង', 'Ingredient'),
  ('CM0164c', 'Shoyu Soy Sauce 500ml', 1.80, 'ដប', 'Ingredient'),
  (NULL, 'Fresh White Child - 500g', 65.00, 'កញ្ចប់', 'Fish'),
  (NULL, '100g Bafun Uni', 75.00, 'ក្រាម', 'Uni - Fresh Urchin'),
  (NULL, '300g bafun uni', 180.00, '300g', 'Uni - Fresh Urchin'),
  (NULL, 'Salt see Uni', 123.00, '100g', 'Uni - Fresh Urchin'),
  (NULL, 'B grade Narabi/B High grade', 135.00, '250g', 'Uni - Fresh Urchin'),
  (NULL, 'B grade bara/B normal grade', 129.00, '300g', 'Uni - Fresh Urchin'),
  (NULL, 'Kiro Narabi/yellow High grade uni', 153.00, '250g', 'Uni - Fresh Urchin'),
  (NULL, 'Canada uni', 120.00, '250g', 'Uni - Fresh Urchin'),
  (NULL, 'Unagi Sauce', 4.60, 'ដប', 'Sauce & Oil'),
  (NULL, 'Hadate No1(Limited)', 860.00, '300g', 'Uni - Fresh Urchin'),
  ('TO001b', 'Frozen Collar of Yellow Tail Fish', 5.40, '100g', 'Fish'),
  ('TO001c', 'Frozen Young Yellowtail Fillet-Tail part', 4.85, '100g', 'Fish'),
  ('MY016b', 'Unagi Grilled eel sauce', 10.80, 'ដប', 'Sauce & Oil'),
  (NULL, 'Mentsuyu Sauce', 4.20, 'ដប', 'Sauce & Oil'),
  (NULL, 'Frozen Octopus with Wasabi 100g', 4.00, 'ប្រអប់', 'Processed Foods'),
  ('AZ020b', 'Frozen Octopus With Wasabi Lite - 500g', 17.00, 'ប្រអប់', 'Processed Foods'),
  (NULL, 'Sparkling Jelly Wine Case', 85.00, 'កេះ', 'Sparkling Wine'),
  (NULL, 'Sumo Citrus', 137.00, 'ប្រអប់', 'Fruits'),
  (NULL, 'Setoka', 206.00, 'ប្រអប់', 'Fruits'),
  (NULL, 'Arita mandarin', 176.00, 'ប្រអប់', 'Fruits'),
  (NULL, 'Japanese Crystal Pomelo', 176.00, 'ប្រអប់', 'Fruits'),
  (NULL, 'Amakusa Orange', 146.00, 'ប្រអប់', 'Fruits'),
  (NULL, 'Loquat', 63.00, 'កញ្ចប់', 'Fruits'),
  (NULL, 'Yotsuboshi Strawberry', 33.00, 'កញ្ចប់', 'Fruits'),
  (NULL, 'Island Berry', 20.00, 'កញ្ចប់', 'Fruits'),
  (NULL, 'Japanese Strawberry', 34.00, 'កញ្ចប់', 'Fruits'),
  (NULL, 'Caviar Baeri Classic - 15g', 50.00, 'កំប៉ុង', 'Caviar'),
  (NULL, 'Caviar Baeri Classic - 50g', 135.00, 'កំប៉ុង', 'Caviar'),
  (NULL, 'Caviar Baeri Classic - 125g', 295.00, 'កំប៉ុង', 'Caviar'),
  (NULL, 'Caviar Baeri Primeur - 50g', 190.00, 'កំប៉ុង', 'Caviar'),
  (NULL, 'Caviar Baeri Vintage - 50g', 185.00, 'កំប៉ុង', 'Caviar'),
  (NULL, 'Caviar Baeri Origin - 50g', 175.00, 'កំប៉ុង', 'Caviar'),
  (NULL, 'Caviar Oscietra - 50g', 205.00, 'កំប៉ុង', 'Caviar'),
  (NULL, 'Caviar Oscietre classic 125g', 295.50, 'កំប៉ុង', 'Caviar'),
  (NULL, 'Caviar Oscietre classic 15g', 55.00, 'កំប៉ុង', 'Caviar'),
  (NULL, 'Caviar Oscietre classic 50g', 135.00, 'កំប៉ុង', 'Caviar'),
  (NULL, 'Caviar Sterlet - 30G', 56.00, 'កំប៉ុង', 'Caviar'),
  (NULL, 'Caviar Sterlet 50g', 85.00, 'កំប៉ុង', 'Caviar'),
  (NULL, 'Caviar Sterlet 200g', 300.00, 'កំប៉ុង', 'Caviar'),
  (NULL, 'Narabi High Grade 250g', 160.00, 'ប្រអប់', 'Uni - Fresh Urchin'),
  (NULL, 'Frozen Young Yellowtail Fillet​ - 1Kg', 55.00, 'គីឡូ', 'Fish'),
  ('AZ045e', 'Azuma Nishin Yellow 1kg (8pcs)', 35.00, 'គីឡូ', 'Fish Roe'),
  (NULL, 'Fresh Salmon Fillet 1Kg', 40.00, 'គីឡូ', 'Fish'),
  (NULL, 'Fresh Bluefin Tuna - 1Kg', 168.00, 'គីឡូ', 'Tuna'),
  ('YA006c', 'Frozen Fatty Bluefin Tuna - Kg', 185.00, 'គីឡូ', 'Tuna'),
  (NULL, 'Frozen Octopus With Wasabi Lite - 100g', 4.00, 'ប្រអប់', 'Processed Foods'),
  ('MY304a', 'Okina Natto Fukuok', 3.90, 'កញ្ចប់', 'Processed Foods'),
  ('AB084a', 'Abashiri Shiretoko Beer - Green Beer', 4.50, 'ដប', 'Beer'),
  ('MM035d', 'Frozen Young Yellowtail Loin', 70.00, 'គីឡូ', 'Fish'),
  (NULL, 'Frozen Octopus With Wasabi Lite - 50g', 2.00, 'ប្រអប់', 'Processed Foods'),
  (NULL, 'Fresh Whole Salmon', 27.00, 'គីឡូ', 'Fish'),
  (NULL, 'Sardine', 81.00, 'គីឡូ', 'Fresh Premium'),
  (NULL, 'Red Crab Fresh - 150g', 24.00, 'ក្បាល', 'Fresh Premium'),
  (NULL, 'Monkfish Liver - 1Kg', 79.00, 'គីឡូ', 'Fresh Premium'),
  (NULL, 'Red Whelk - 80g', 85.00, 'គីឡូ', 'Fresh Premium'),
  (NULL, 'White Tilefish', 135.00, 'គីឡូ', 'Fresh Premium'),
  (NULL, 'Sasa Flounder', 85.00, 'គីឡូ', 'Fresh Premium'),
  (NULL, 'Sweet Shrimp - 15g', 125.00, 'គីឡូ', 'Fresh Premium'),
  (NULL, 'Ark Shell - Brand:Yuriage', 125.00, 'គីឡូ', 'Fresh Premium'),
  (NULL, 'Clam Asari - 30g', 89.00, 'គីឡូ', 'Fresh Premium'),
  ('BU089a', 'Hibiki Japanese Harmony', 185.00, 'ដប', 'Japanese Whisky'),
  ('CM0228a', 'Kacha Umesyu Plum In', 7.70, 'ដប', 'Plum Wine & Liqueur'),
  ('NF001e', 'Kishu Nanko Ripe Plum Wine 5 year', 148.00, 'ដប', 'Plum Wine & Liqueur'),
  ('NF001d', 'Kishu Nanko Ripe Plum Wine', 57.00, 'ដប', 'Plum Wine & Liqueur'),
  ('NF003a', 'Nakata Umeshu Plum Wine', 25.50, 'ដប', 'Plum Wine & Liqueur'),
  ('NF002a', 'Nakata Kishu Plum wine with Plum Fruit', 22.50, 'ដប', 'Plum Wine & Liqueur'),
  ('NF001b', 'Nakata Kishu Plum wine with Plum Fruit 84ml', 4.00, 'ដប', 'Plum Wine & Liqueur'),
  (NULL, 'Sea Bass - 5Kg', 75.00, 'គីឡូ', 'Fresh Premium'),
  (NULL, 'Chicken Grunt - 140g', 85.00, 'គីឡូ', 'Fresh Premium'),
  (NULL, 'Greater Amberjack - 4Kg', 95.00, 'គីឡូ', 'Fresh Premium'),
  (NULL, 'Spanish Mackerel - 3Kg', 89.00, 'គីឡូ', 'Fresh Premium'),
  (NULL, 'Lethrinus Haematopterus - 6Kg', 90.00, 'គីឡូ', 'Fresh Premium'),
  (NULL, 'Red Sea Bream - 3Kg', 75.00, 'គីឡូ', 'Fresh Premium'),
  (NULL, 'Fresh Water Clam - 1Kg', 70.00, 'គីឡូ', 'Fresh Premium'),
  (NULL, 'Surf Clam - 240g', 70.00, 'គីឡូ', 'Fresh Premium'),
  (NULL, 'Parrot Fish - 1Kg', 90.00, 'គីឡូ', 'Fresh Premium'),
  (NULL, 'Monkfish - 5.4-8Kg', 75.00, 'គីឡូ', 'Fresh Premium'),
  (NULL, 'Japanese Smelt - 8-10Cm', 70.00, 'គីឡូ', 'Fresh Premium'),
  (NULL, 'Cardinal Fish - 2-2.5Kg', 110.00, 'គីឡូ', 'Fresh Premium'),
  (NULL, 'Striped Horse Mackerel - 1.5Kg', 150.00, 'គីឡូ', 'Fresh Premium'),
  (NULL, 'Pomfret - 1.5Kg', 90.00, 'គីឡូ', 'Fresh Premium'),
  (NULL, 'Wagyu Sirloin A4 - 100g', 150.00, 'គីឡូ', 'Meat & Poultry'),
  (NULL, 'Frozen A5 Miyazaki Tenderloin', 190.00, 'គីឡូ', 'Meat & Poultry'),
  (NULL, 'Valentine Uni', 49.00, 'ក្រាម', 'Uni - Fresh Urchin'),
  (NULL, 'Frozen Oyster With Shell Size 2S', 29.00, 'កញ្ចប់', 'Shell'),
  (NULL, 'Shisamo Fish Roe 200g', 7.50, 'ប្រអប់', 'Fish Roe'),
  (NULL, 'Kirin Ichiban Shibori-600ml', 6.00, 'ដប', 'Beer'),
  (NULL, 'JP BBQ Sauce', 4.50, 'pcs', 'Sauce & Oil'),
  (NULL, 'Abashiri beer Ryuhyo draft bottle - Blue beer', 5.00, 'ដប', 'Beer'),
  (NULL, 'Fresh Mackerel', 99.00, 'Kg', 'Fresh Premium'),
  (NULL, 'Abashiri beer Ryuhyo draft Can - Blue beer', 3.00, 'កំប៉ុង', 'Beer'),
  (NULL, 'Spaghetti - 500g', 2.30, 'ប្រអប់', 'Dried Items'),
  (NULL, 'Fresh Tuna', 175.00, 'គីឡូ', 'Tuna'),
  (NULL, 'Golden Sea Bream', 140.00, 'គីឡូ', 'Fresh Premium'),
  (NULL, 'Ami Nodoguro', 250.00, 'គីឡូ', 'Fresh Premium'),
  ('AZ014a', 'Azuma Konjac Squid', 9.50, 'ដុំ', 'Processed Foods'),
  ('Az014b', 'Azuma Konjac Salmon', 9.50, 'ដុំ', 'Processed Foods'),
  ('Az014c', 'Azuma Konjac Tuna', 9.50, 'ដុំ', 'Processed Foods'),
  ('NR037i', 'Frozen Salmon 25g - Limited', 4.00, 'កំប៉ុង', 'Fish Roe'),
  (NULL, 'Nabeshima Daiginjyo - 720ml', 95.00, 'ដប', 'Sake'),
  (NULL, 'Nabeshima Tokubetsu-Jyumaisyu -​ 720ml', 39.00, 'ដប', 'Sake'),
  (NULL, 'Nabeshima Daiginjyo - 1.8L', 209.00, 'ដប', 'Sake'),
  (NULL, 'Nabeshima Black Label​ - 720ml', 499.00, 'ដប', 'Sake'),
  (NULL, 'Nabeshima Akaiwaomachi - 1.8L', 135.00, 'ដប', 'Sake'),
  (NULL, 'Nabeshima Akaiwaomachi​ - 720ml', 75.00, 'ដប', 'Sake'),
  (NULL, 'Nabeshima Aiyama - 1.8L', 195.00, 'ដប', 'Sake'),
  (NULL, 'Nabeshima Aiyama​ - 720ml', 95.00, 'ដប', 'Sake'),
  (NULL, 'Suigei Yuzu - 720ml', 25.00, 'ដប', 'Sake'),
  (NULL, 'Suigei Tokubetsu Junmai - 720ml', 35.00, 'ដប', 'Sake'),
  (NULL, 'Suigei Tokubetsu Junmai - 300ml', 15.00, 'ដប', 'Sake'),
  (NULL, 'Suigei Junmaisyu Renowa - 1.8L', 75.00, 'ដប', 'Sake'),
  (NULL, 'Suigei Junmaisyu Renowa - 720ml', 35.00, 'ដប', 'Sake'),
  (NULL, 'Suigei Junmai Ginjo Ginrei - 1.8L', 75.00, 'ដប', 'Sake'),
  (NULL, 'Suigei Junmai Ginjo Ginrei - 720ml', 35.00, 'ដប', 'Sake'),
  (NULL, 'Suigei Junmai Ginjo Ginrei - 300ml', 15.00, 'ដប', 'Sake'),
  (NULL, 'Suigei Junmai Daiginjyo Ya - 720ml', 109.00, 'ដប', 'Sake'),
  (NULL, 'Suigei Junmai Daiginjyo Sho - 720ml', 79.00, 'ដប', 'Sake'),
  (NULL, 'Suigei Junmai Daiginjyo Man - 720ml', 175.00, 'ដប', 'Sake'),
  (NULL, 'Suigei Junmai Daiginjyo Daito - 720ml', 355.00, 'ដប', 'Sake'),
  (NULL, 'Frozen Kaki Oyster 2L - 500g', 15.00, 'កញ្ចប់', 'Shell'),
  (NULL, 'JFDA Tempura Flour - 100g', 0.66, 'កញ្ចប់', 'Rice & Flour'),
  (NULL, 'Future Fish Octopus', 9.00, 'កញ្ចប់', 'Future Fish'),
  ('AZ014c', 'Future Fish Salmon', 9.00, 'កញ្ចប់', 'Future Fish'),
  ('AZ014b', 'Future Fish Tuna', 9.00, 'កញ្ចប់', 'Future Fish'),
  (NULL, 'Future Fish', 9.00, 'pcs', 'Future Fish'),
  (NULL, 'Frozen Grilled Eel Fillet ( Slice)', 2.91, 'កញ្ចប់', 'Fish'),
  (NULL, 'Shisamo Fish Roe 100g', 4.00, 'ប្រអប់', 'Fish Roe'),
  ('AKC038b', 'Japonica White Rice (Premium)', 2.00, 'គីឡូ', 'Rice & Flour'),
  (NULL, 'Uni-50g.', 35.00, '50g', 'Uni - Fresh Urchin'),
  (NULL, 'Sashimi Set S​ - B16', 25.00, 'ប្រអប់', 'Sashimi Set'),
  (NULL, 'Sashimi Set L​ - B17', 50.00, 'ប្រអប់', 'Sashimi Set'),
  (NULL, 'Tobiko Orange 50g', 4.00, 'កំប៉ុង', 'Fish Roe'),
  (NULL, 'Frozen Capelin Roe - Green 50g', 2.00, 'កំប៉ុង', 'Fish Roe'),
  (NULL, 'B18 - Hamachi Set', 25.00, 'ឈុត', 'Sashimi Set'),
  (NULL, 'B19 - Lean Bluefin Tuna Set', 30.00, 'ឈុត', 'Sashimi Set'),
  (NULL, 'B20 - Medium Bluefin Tuna Set', 35.00, 'ឈុត', 'Sashimi Set'),
  (NULL, 'B21 - Fatty Bluefin Tuna Set', 40.00, 'ឈុត', 'Sashimi Set'),
  (NULL, 'Suntry Premium Malt White 350ml', 3.50, 'កំប៉ុង', 'Beer'),
  (NULL, 'Suntry Premium Malt Black 350ml', 4.20, 'កំប៉ុង', 'Beer'),
  (NULL, 'Azuma Nishin Yellow 1pc', 5.50, 'ដុំ', 'Fish Roe'),
  (NULL, 'Frozen No Shell Scallop 200g', 15.00, 'កញ្ចប់', 'Shell'),
  ('ASS001a', 'Asan Unagi Sauce 1L', 9.50, 'btl', 'Sauce & Oil'),
  (NULL, 'Pink Sliced Ginger Pickle 100g', 0.43, 'កំប៉ុង', 'Processed Foods'),
  (NULL, 'Salted Squid 250g', 12.00, 'កំប៉ុង', 'Processed Foods'),
  (NULL, 'B22 - Salmon Tofu Set', 18.00, 'ឈុត', 'Sashimi Set'),
  (NULL, 'B23 - Fatty Bluefin Tuna Tofu Set', 25.00, 'ឈុត', 'Sashimi Set'),
  (NULL, 'B24-Hamachi and Fatty tuna set', 35.00, 'ឈុត', 'Sashimi Set'),
  (NULL, 'Fresh Sea Grape 50g', 1.20, 'ប្រអប់', 'Vegetables'),
  (NULL, 'Fresh Sea Grapes 100g', 2.40, 'ប្រអប់', 'Vegetables'),
  (NULL, 'Yellowfin Tuna Kg', 26.00, 'គីឡូ', 'Tuna'),
  (NULL, 'B25 - Tuna & Hamachi Sashimi', 49.99, 'ឈុត', 'Tuna Sashimi Set'),
  (NULL, 'B26 - Tuna & Hamachi Sashimi S', 28.99, 'ឈុត', 'Tuna Sashimi Set'),
  (NULL, 'B27 - Medium Tuna Sashimi', 42.99, 'ឈុត', 'Tuna Sashimi Set'),
  (NULL, 'Omakase Set - A', 15.00, 'ឈុត', 'ឈុតអូម៉ាកាសិ'),
  (NULL, 'Omakase Set - B', 25.00, 'ឈុត', 'ឈុតអូម៉ាកាសិ'),
  (NULL, 'Japaness sweet photato - chilled', 10.00, 'គីឡូ', 'Vegetables'),
  (NULL, 'Orange Masago 500g', 20.00, 'ប្រអប់', 'Fish Roe'),
  (NULL, 'Hamanaka Murasaki 250g', 150.00, 'ប្រអប់', 'Uni - Fresh Urchin'),
  (NULL, 'Mashed Potatos', 2.40, 'ដុំ', 'Dessert'),
  (NULL, 'Nigiri and Salmon Maki Set 14pc', 13.00, 'ប្រអប់', 'Sushi Set'),
  (NULL, 'Japonica White Rice Premium - Big Box', 0.50, 'ប្រអប់', 'Rice & Flour'),
  (NULL, 'Japonica White Rice Premium - Small Box', 0.25, 'ប្រអប់', 'Rice & Flour'),
  (NULL, 'Orange Masago 50g', 2.00, 'កំប៉ុង', 'Fish Roe'),
  (NULL, 'Gunkanmaki Set', 12.00, 'ប្រអប់', 'Sushi Set'),
  (NULL, 'Salted Squid 100g', 4.50, 'កំប៉ុង', 'Processed Foods'),
  (NULL, 'Salmon Maki 8​pc', 2.87, 'ប្រអប់', 'Sushi Set'),
  (NULL, 'Sushi Set A​ (L)', 27.00, 'ប្រអប់', 'Sushi Set'),
  (NULL, 'Sushi Set A (S)', 15.00, 'ប្រអប់', 'Sushi Set'),
  (NULL, 'Sushi Set B (L)', 35.00, 'ប្រអប់', 'Sushi Set'),
  (NULL, 'Sushi Set B (S)', 18.00, 'ប្រអប់', 'Sushi Set'),
  (NULL, 'Sushi Set C', 35.00, 'ប្រអប់', 'Sushi Set'),
  (NULL, 'Sushi Set D', 40.00, 'ប្រអប់', 'Sushi Set'),
  (NULL, 'Frozen Mentaiko Paste - 100g', 8.00, 'កញ្ចប់', 'Fish Roe'),
  (NULL, 'Frozen Shrimp Roe 100g', 4.50, 'ប្រអប់', 'Fish Roe'),
  (NULL, 'Ogawa Murasaki Narabi 250g', 110.00, 'ប្រអប់', 'Uni - Fresh Urchin'),
  (NULL, 'Fresh Uni - 60g', 45.00, 'ប្រអប់', 'Uni - Fresh Urchin'),
  (NULL, 'Ogawa Company Narabi (Yellow)', 145.00, 'ប្រអប់', 'Uni - Fresh Urchin'),
  (NULL, 'Marui Ishida (B Grade) - 250g', 125.00, 'ប្រអប់', 'Uni - Fresh Urchin'),
  (NULL, 'Ichikawa Murasaki Narabi - 250g', 140.00, 'pkt', 'Uni - Fresh Urchin'),
  (NULL, 'Edamame - 250g', 1.60, 'កញ្ចប់', 'Processed Foods'),
  (NULL, 'Shime Saba Set', 12.90, '​ឈុត', 'Sashimi Set'),
  (NULL, 'Azuma Nishin Yellow Set', 14.90, 'ឈុត', 'Sashimi Set'),
  (NULL, 'Plant-Based Tuna Set', 11.90, 'ឈុត', 'Sashimi Set'),
  (NULL, 'Plant-Based Squid Set', 11.90, 'ឈុត', 'Sashimi Set'),
  (NULL, 'Plant-Based Salmon Set', 11.90, 'ឈុត', 'Sashimi Set'),
  (NULL, 'Katsuo Tataki Set', 14.90, 'ឈុត', 'Sashimi Set'),
  (NULL, 'Octopus Sliced Set', 13.90, 'ឈុត', 'Sashimi Set'),
  (NULL, 'Hamachi Fillet Set', 14.90, 'ឈុត', 'Sashimi Set'),
  (NULL, '​Kisu Fillet Set', 17.90, 'ឈុត', 'Sashimi Set'),
  (NULL, 'Frozen Botan Ebi - 500g', 55.00, 'ប្រអប់', 'Shrimp'),
  (NULL, 'Frozen Fried Bean Curd (Kanto)', 5.00, 'កញ្ចប់', 'Processed Foods'),
  (NULL, 'Maruko SP Kimetsugara Russia (Red)', 294.00, 'ប្រអប់', 'Uni - Fresh Urchin'),
  (NULL, 'Mentaiko - 20g', 1.60, 'កញ្ចប់', 'Fish Roe'),
  (NULL, 'Frozen crab butter - 10g', 1.80, 'pcs', 'Fish'),
  (NULL, 'Frozen Botan Ebi - 500g (Limited)', 35.00, 'ប្រអប់', 'Shrimp'),
  (NULL, 'Kirin Beer Harekaze - 350ml', 90.00, 'កេស', 'Beer'),
  (NULL, 'Uni Kaneyo', 165.00, '250g', 'Uni - Fresh Urchin'),
  (NULL, 'Ogawa Bara', 148.00, 'ប្រអប់', 'Uni - Fresh Urchin'),
  (NULL, 'Frozen Buri Terriyaki - 200g', 10.40, 'កញ្ចប់', 'Fish'),
  (NULL, 'Suntory The Premium Malt’s - 350ml (Case)', 75.00, 'កេស', 'Beer'),
  (NULL, 'Suntory The Premium Malt''s Kaoru Ale - 350ml (Case)', 70.00, 'កេស', 'Beer'),
  (NULL, 'Kirin Spring Valley Hojun 496 - 350ml (Case)', 90.00, 'កេស', 'Beer'),
  (NULL, 'Kirin Spring Valley Silk Ale White - 350ml (Case)', 90.00, 'កេស', 'Beer'),
  (NULL, 'Suntory The Premium Malt''s Suzunone Ale - 350ml (Case)', 90.00, 'កេស', 'Beer'),
  (NULL, 'Suntory The Premium Malt''s Akane-Iro Ale - 350ml (Case)', 90.00, 'កេស', 'Beer'),
  (NULL, 'The Premium Malt''s sea side Ale - 350ml (Case)', 90.00, 'កេស', 'Beer'),
  (NULL, 'Sapporo Yebisu Citrus Blanc - 350ml (Case)', 90.00, 'កេស', 'Beer'),
  (NULL, 'KIRIN Ichiban Shibori <Kuronama> - 350ml (Case)', 70.00, 'កេស', 'Beer'),
  (NULL, 'KIRIN Akiaji - 350ml (Case)', 90.00, 'កេស', 'Beer'),
  (NULL, 'KIRIN Ichiban Shibori​ - 350ml (pack)', 17.50, 'យួរ', 'Beer'),
  (NULL, 'Yebisu Beer - 350ml (Pack)', 20.50, 'យួរ', 'Beer'),
  (NULL, 'Suntory The Premium Malt''s - 350ml (Pack)', 20.00, 'យួរ', 'Beer'),
  (NULL, 'Suntory The Premium Malt''s Kaoru Ale - 350ml (Pack)', 17.50, 'យួរ', 'Beer'),
  (NULL, 'Kirin Spring Valley Hojun 496 - 350ml (Pack)', 22.50, 'យួរ', 'Beer'),
  (NULL, 'Kirin Spring Valley Silk Ale White - 350ml (Pack)', 22.50, 'យួរ', 'Beer'),
  (NULL, 'Suntory The Premium Malt''s Suzunone Ale - 350ml (Pack)', 22.50, 'យួរ', 'Beer'),
  (NULL, 'Suntory The Premium Malt''s Akane-Iro Ale - 350ml (Pack)', 22.50, 'យួរ', 'Beer'),
  (NULL, 'The Premium Malt''s sea side Ale - 350ml (Pack)', 22.50, 'យួរ', 'Beer'),
  (NULL, 'Sapporo Yebisu Citrus Blanc - 350ml (Pack)', 22.50, 'យួរ', 'Beer'),
  (NULL, 'KIRIN Ichiban Shibori<Kuronama> - 350ml (Pack)', 17.50, 'យួរ', 'Beer'),
  (NULL, 'KIRIN Akiaji - 350ml (Pack)', 22.50, 'យួរ', 'Beer'),
  (NULL, 'KIRIN Ichiban Shibori - 350ml (Case)', 70.00, 'កេស', 'Beer'),
  (NULL, 'KIRIN Ichiban Shibori - 350ml (Pack)', 17.50, 'យួរ', 'Beer'),
  (NULL, 'Yebisu Beer - 350ml (Case)', 79.00, 'កេស', 'Beer'),
  ('HC001a', 'Fresh Whole Salmon JP', 60.00, 'Kg', 'Fish'),
  (NULL, 'Wagyu Sirloin/Striploin (A4)​​ - G', 14.00, 'ក្រាម', 'Meat & Poultry'),
  (NULL, 'Maruki Hirakawa Russia Bafun 400g', 295.00, 'ប្រអប់', 'Uni - Fresh Urchin'),
  (NULL, 'Kanetatsu Russia Bafun 400g', 295.00, 'ប្រអប់', 'Uni - Fresh Urchin'),
  (NULL, 'Gunkan Maki 14pc', 20.00, 'ប្រអប់', 'Sushi Set'),
  (NULL, 'Gunkan Maki 8pc', 14.00, 'ប្រអប់', 'Sushi Set'),
  (NULL, 'Gunkan Maki 20pc', 26.00, 'ប្រអប់', 'Sushi Set'),
  (NULL, 'Frozen Octopus With Wasabi Lite 250g', 9.00, 'ប្រអប់', 'Processed Foods'),
  (NULL, 'SOUHANA JUNMAI DAIGINJO', 59.00, 'ដប', 'Sake'),
  (NULL, 'SOUHANA JUNMAI GINJO', 35.00, 'ដប', 'Japanese Sake'),
  (NULL, 'FUGA JUNMAI DAIGINJO', 55.00, 'ដប', 'Sake'),
  (NULL, 'SAKARI NO.13 JUNMAI GINJO', 29.00, 'ដប', 'Sake'),
  (NULL, 'SAKARI NO.14. JUNMAI', 25.00, 'ដប', 'Sake'),
  (NULL, 'SAKARI NO.21 YUZU', 19.00, 'ដប', 'Sake'),
  (NULL, 'NAMA-GENSHU HONJOZO', 9.00, 'ដប', 'Sake'),
  (NULL, 'NAMA-GENSHU DAIGINJO', 9.00, 'ដប', 'Sake'),
  (NULL, 'NAMA-GENSHU JUNMAI GINJO', 9.00, 'ដប', 'Sake'),
  (NULL, 'NAMA-GENSHU JUNMAI DAIGINJO', 9.00, 'ដប', 'Sake'),
  (NULL, 'SAKARI GIN "SHUKUGAWA"', 45.00, 'ដប', 'Japanese Sake'),
  (NULL, 'TOKUSEN HONJOZO', 25.00, 'ដប', 'Sake'),
  (NULL, 'JOSEN KARAKUCHI', 25.00, 'ដប', 'Sake'),
  (NULL, 'SAKARI NO.21 YUZU - 720ml', 35.00, 'ដប', 'Sake'),
  (NULL, 'SAKARI NO.11 JUNMAI DAIGINJO - 300ml', 15.00, 'ដប', 'Japanese Sake'),
  (NULL, 'SAKARI NO.12 DAIGINJO', 29.00, 'ដប', 'Sake'),
  (NULL, 'SAKARI NO.11 JUNMAI DAIGINJO 720ml', 35.00, 'ដប', 'Sake'),
  (NULL, 'Suntory The Premium Malt''s Sea Side Ale - 350ml (Pack)', 22.50, 'can', 'Beer'),
  (NULL, 'Hadate Hokkaido 300g', 750.00, 'Pkt', 'Uni - Fresh Urchin'),
  (NULL, 'Abashiri Shiretoko Beer - Green Beer (Case)', 105.00, 'កេស', 'Beer'),
  (NULL, 'Kaneki Kimura Russia Bafun 400g', 310.00, 'ប្រអប់', 'Uni - Fresh Urchin'),
  (NULL, 'Kirin Beer Harekaze - 350ml Pack', 22.50, 'យូរ', 'Beer'),
  (NULL, 'Add on Sashimi +1', 6.00, 'ឈុត', 'Sashimi Set'),
  (NULL, 'Add on Sashimi +2', 10.00, 'ឈុត', 'Sashimi Set'),
  (NULL, 'Add on Sashimi +3', 15.00, 'ឈុត', 'Sashimi Set'),
  (NULL, 'Inari Sushi Set (6pc)', 19.00, 'ប្រអប់', 'Sushi Set'),
  (NULL, 'Inari Sushi Set (12pc)', 35.00, 'ប្រអប់', 'Sushi Set'),
  (NULL, 'Maruki Hirakawa Hokkaido 400g', 310.00, 'ប្រអប់', 'Uni - Fresh Urchin'),
  (NULL, 'Nabeshima Daiginjo (Buy 1 get 3) (Uni Set)', 85.00, 'ដប', 'Sake Promotion'),
  (NULL, 'Nabeshima Daiginjo (Buy 1 get 3) (Nakata Set)', 85.00, 'ដប', 'Sake Promotion'),
  (NULL, 'Nabeshima Daiginjo (Buy 1 get 3) (Daifuku Set)', 85.00, 'ដប', 'Sake Promotion'),
  (NULL, 'Nabeshima Daiginjo (Buy 1 get 3) (Tako Wasabi Set)', 85.00, 'ដប', 'Sake Promotion'),
  (NULL, 'Jack Daniel''s Coca Cola Zero Sugar', 2.50, 'កំប៉ុង', 'Plum Wine & Liqueur'),
  (NULL, 'Kanetatsu 250g', 168.00, 'ប្រអប់', 'Uni - Fresh Urchin'),
  (NULL, 'Maruki Suisan Narabi 250g', 168.00, 'ប្រអប់', 'Uni - Fresh Urchin'),
  (NULL, 'Coca-Cola Jack Daniel''s', 2.50, 'កំប៉ុង', 'Beer'),
  (NULL, 'Salmon Set (11$)', 11.00, 'ឈុត', 'Sashimi Set'),
  (NULL, 'Yellow Nishin Set (18$)', 18.00, 'ឈុត', 'Sashimi Set'),
  (NULL, 'Hamachi Set (18$)', 18.00, 'ឈុត', 'Sashimi Set'),
  (NULL, 'Chutoro Set (31$)', 31.00, 'ឈុត', 'Sashimi Set'),
  (NULL, 'Sashimi add-on set (8$)', 8.00, 'ឈុត', 'Sashimi Set'),
  (NULL, 'Marukawa Bara 250g', 178.00, 'ប្រអប់', 'Uni - Fresh Urchin'),
  (NULL, 'Maruki Hirakawa Hamanaka farmed Bafun 400g', 580.00, 'ប្រអប់', 'Uni - Fresh Urchin'),
  (NULL, 'Maruichi Bara Uni (red) 250g', 225.00, 'ប្រអប់', 'Uni - Fresh Urchin'),
  (NULL, 'Jack Daniel''s Coca Cola Zero Sugar 350ml', 4.00, 'កំប៉ុង', 'Plum Wine & Liqueur'),
  (NULL, 'Jack Daniel''s Coca Cola 160ml', 2.50, 'កំប៉ុង', 'Plum Wine & Liqueur'),
  (NULL, 'Hiryu Russia Mix Narabi 250g', 138.00, 'ប្រអប់', 'Uni - Fresh Urchin'),
  (NULL, 'Jack Daniel''s Coca Cola 160ml (case)', 70.00, 'កេស', 'Plum Wine & Liqueur'),
  (NULL, 'Jack Daniel''s Coca Cola Zero Sugar 160ml (case)', 70.00, 'កេស', 'Plum Wine & Liqueur'),
  (NULL, 'Jack Daniel''s Coca Cola Zero Sugar 350ml (Case)', 90.00, 'កេស', 'Plum Wine & Liqueur'),
  (NULL, 'Maruko Narabi Mix 250g', 145.00, '1', 'Uni - Fresh Urchin'),
  (NULL, 'Frozen No Shell Scallop 150g', 12.00, 'កញ្ចប់', 'Shell'),
  (NULL, 'Kaneki Kimura Narabi 250g', 150.00, 'pcs', 'Uni - Fresh Urchin'),
  (NULL, 'Asahi Future Lemon Sour 345ml (Plain)', 5.50, 'កំប៉ុង', 'Beer'),
  (NULL, 'Asahi Future Lemon Sour  345ml (Original)', 5.50, 'កំប៉ុង', 'Beer'),
  (NULL, 'Asahi Future Lemon Sour (Plain) - Case', 130.00, 'កេស', 'Beer'),
  (NULL, 'Asahi Future Lemon Sour (Original) - Case', 130.00, 'កេស', 'Beer'),
  (NULL, 'Jack Daniel''s Coca Cola 350ml (Case)', 90.00, 'កេស', 'Plum Wine & Liqueur'),
  (NULL, 'Abashiri beer Ryuhyo draft Can - Blue beer (Case)', 70.00, 'កេស', 'Beer'),
  (NULL, 'Jim Beam Highball Peach 350ml', 3.00, 'កំប៉ុង', 'Plum Wine & Liqueur'),
  (NULL, 'Jim Beam Highball Peach 350ml (case)', 70.00, 'កេស', 'Plum Wine & Liqueur'),
  (NULL, 'Jim Beam Highball Honey 350ml', 3.00, 'កំប៉ុង', 'Plum Wine & Liqueur'),
  (NULL, 'Jim Beam Highball Honey 350ml (Case)', 70.00, 'កេស', 'Plum Wine & Liqueur'),
  (NULL, 'Asahi Super Dry 135ml', 2.00, 'កំប៉ុង', 'Beer'),
  (NULL, 'Asahi Super Dry 135ml (case)', 45.00, 'កេស', 'Beer'),
  (NULL, 'Yamata Takizawa Narabi (yellow) 250g', 145.00, 'ប្រអប់', 'Uni - Fresh Urchin'),
  (NULL, 'Jack Daniel''s Coca Cola 350ml', 4.00, 'កំប៉ុង', 'Plum Wine & Liqueur'),
  (NULL, 'Engawa Ikura Gunkan Sushi', 25.00, 'Set', 'Engawa Ikura Gunkan Sushi'),
  (NULL, 'Engawa and Hamachi Sashimi', 35.00, 'set', 'Engawa Ikura Gunkan Sushi'),
  (NULL, 'ITO EN Instant Green Tea with Matcha (Stick)', 29.00, 'ប្រអប់', 'Beverage'),
  (NULL, 'Engawa Ikura Gunkan Sushi 10pc', 25.00, 'ប្រអប់', 'Sushi Set'),
  (NULL, 'Engawa Hamachi Sashimi', 35.00, 'ប្រអប់', 'Sashimi Set'),
  (NULL, 'Yakishushi Nori (50pc)', 15.00, 'កញ្ចប់', 'Dried Items'),
  (NULL, 'Yakisushi Nori 20pc (limited)', 1.50, 'កញ្ចប់', 'Dried Items'),
  (NULL, 'Economy Nori Half Cut (20pc)', 1.50, 'កញ្ចប់', 'Dried Items'),
  (NULL, 'Wagyu A5 Miyazaki', 190.00, 'គីឡូ', 'Meat & Poultry'),
  (NULL, 'Suntory Umeshu Sour 350ml', 2.50, 'កំប៉ុង', 'Beverage'),
  (NULL, 'Suntory Umeshu Sour 350ml (case)', 55.00, 'កេស', 'Beverage'),
  (NULL, 'KIRIN Lemon Sour (Chuhai) 350ml', 3.00, 'កំប៉ុង', 'Plum Wine & Liqueur'),
  (NULL, 'KIRIN Lemon Sour (Chuhai) 350ml - Case', 70.00, 'កេស', 'Plum Wine & Liqueur'),
  (NULL, 'Asahi Super Dry 135ml (pack)', 11.00, 'យួរ', 'Beer'),
  (NULL, 'Asahi Dry Zero Non-Alcohol Drink 350ml', 19.00, 'យួរ', 'Beer'),
  (NULL, 'Asahi Dry Zero Non-Alcohol Drink 350ml (case)', 70.00, 'កេស', 'Beer'),
  (NULL, 'Hanayaka Honjozo 180ml (Blue)', 5.00, 'ដប', 'Japanese Sake'),
  (NULL, 'Hanayaka Junmai 180ml​ (Pink)', 5.00, 'ដប', 'Japanese Sake'),
  (NULL, 'Matsuura SP Narabi 250g', 150.00, 'ប្រអប់', 'Uni - Fresh Urchin'),
  (NULL, 'Katakura Miyagi Mutenka Narabi (Murasaki) 250g', 145.00, 'ប្រអប់', 'Uni - Fresh Urchin'),
  (NULL, 'Uni 100g Tanigawa', 75.00, 'ប្រអប់', 'Uni - Fresh Urchin'),
  (NULL, 'Koh Kong Sauce 1btl', 2.00, 'ដប', 'Sauce & Oil'),
  (NULL, 'Sauce Set', 0.30, 'ឈុត', 'Sauce & Oil'),
  (NULL, 'Vegetables Set', 0.04, 'ប្រអប់', 'Vegetables'),
  (NULL, 'Fried Garlic (additional item)', 0.25, 'កំប៉ុង', 'Dried Items'),
  (NULL, 'Unagi Sauce (Additional Items)', 0.36, 'កំប៉ុង', 'Sauce & Oil'),
  (NULL, 'Ogawa Syoten Hokkaido Narabi (Murasaki) 250g', 150.00, 'ប្រអប់', 'Uni - Fresh Urchin'),
  (NULL, 'Suntory Kaku Highball Dark Color (500ml) - Case', 125.00, 'កេស', 'Plum Wine & Liqueur'),
  (NULL, 'Kuromaru (Black garlic) - 40g', 9.50, 'កញ្ចប់', 'Dried Items'),
  (NULL, 'Frozen Salmon Roe - 50g (Limited)', 8.00, 'កំប៉ុង', 'Fish Roe'),
  (NULL, 'Hokkigai Surl clam 200g', 10.00, 'ឈុត', 'Shell'),
  (NULL, 'Yebisu Beer - 350ml (can)', 3.45, 'កំប៉ុង', 'Beer'),
  (NULL, 'Suntory Kaku Highball Dark Color (500ml) - Can', 5.50, 'កំប៉ុង', 'Plum Wine & Liqueur'),
  (NULL, 'Nakata Apple And Prune Liquor- 180ml', 5.50, 'ដប', 'Plum Wine & Liqueur'),
  (NULL, 'Engawa 250g', 18.00, 'ឈុត', 'Fish'),
  (NULL, 'Nakata Peach and Prune Liquor 180ml', 5.50, 'ដប', 'Plum Wine & Liqueur'),
  (NULL, 'Yamata Takizawa Purple Narabi 250g', 165.00, 'ប្រអប់', 'Uni - Fresh Urchin'),
  (NULL, 'Sato Murasaki Uni - 250g', 150.00, 'ប្រអប់', 'Uni - Fresh Urchin'),
  (NULL, 'Kishu plum wine (White)', 6.00, 'ដប', 'Plum Wine & Liqueur'),
  (NULL, 'Azuma Tako-Cheese salad 1kg', 25.00, 'គីឡូ', 'Processed Foods'),
  (NULL, 'Azuma Tako-Cheese Salad 250g', 6.50, 'កំប៉ុង', 'Processed Foods'),
  (NULL, 'Marukita Muraski Narabi (Russia) 250g', 165.00, 'ប្រអប់', 'Uni - Fresh Urchin'),
  (NULL, 'Maruki Hirakawa Russia Narabi - 250g', 165.00, 'ប្រអប់', 'Uni - Fresh Urchin'),
  (NULL, 'Kaneyo-ouyou Narabi Purple (Hokkaido) - 250g', 170.00, 'ប្រអប់', 'Uni - Fresh Urchin'),
  (NULL, 'Boiled Octopus with Wasabi​ 100g', 0.60, 'កំប៉ុង', 'Processed Foods'),
  (NULL, 'Boiled Octopus with Wasabi 250g', 1.80, 'កំប៉ុង', 'Processed Foods'),
  (NULL, 'Boiled Octopus with Wasabi 1kg', 6.50, 'កញ្ចប់', 'Processed Foods'),
  (NULL, 'Nabeshima 100th Anniversary', 219.00, 'ដប', 'Sake'),
  (NULL, 'Ogawa Hamanaka Rishiri Rebun Narabi (Purple) 250g', 165.00, 'ប្រអប់', 'Uni - Fresh Urchin'),
  (NULL, 'Daiyame Imo Shochu​ 900ml', 25.00, 'ដប', 'Plum Wine & Liqueur'),
  (NULL, 'CHILL GREEN spicy & citrus 720ml', 25.00, 'ដប', 'Plum Wine & Liqueur'),
  (NULL, 'CHILL GREEN Bitter＆ Tropical 900ml', 55.00, 'ដប', 'Plum Wine & Liqueur'),
  (NULL, 'Kurokirishima Shochu Imo 720ml', 25.00, 'ដប', 'Plum Wine & Liqueur'),
  (NULL, 'Kurokirishima Shochu Imo 1.8L', 40.50, 'ដប', 'Plum Wine & Liqueur'),
  (NULL, 'Iichiko silhouette 720ml', 25.00, 'ដប', 'Plum Wine & Liqueur'),
  (NULL, 'Akane Kirishima 900ml', 55.00, 'ដប', 'Plum Wine & Liqueur'),
  (NULL, 'Umeshu Honey 720ml', 25.00, 'ដប', 'Plum Wine & Liqueur'),
  (NULL, 'Yokubarihime Torokoku mix 180ml', 5.50, 'ដប', 'Plum Wine & Liqueur'),
  (NULL, 'Kishu plum wine (Red) 180ml', 6.00, 'ដប', 'Plum Wine & Liqueur'),
  (NULL, 'Nakata Kishu Plum wine honey 180ml', 6.00, 'ដប', 'Plum Wine & Liqueur'),
  (NULL, 'Kaneshinn Hokkaido Bara (Purple) 250g', 115.00, 'ប្រអប់', 'Uni - Fresh Urchin'),
  (NULL, 'Suntory Chita 700ml', 110.00, 'ដប', 'Japanese Whisky'),
  (NULL, 'Miyagikyo Single Malt 700ml', 110.00, 'ដប', 'Japanese Whisky'),
  (NULL, 'Nikka Yoichi 700មល', 110.00, 'ដប', 'Japanese Whisky'),
  (NULL, 'Nabeshima Junmai Ginjo Yamada Nishiki 720ml', 50.00, 'ដប', 'Sake'),
  (NULL, 'Nabeshima Junmai Daiginjo 45% - 720ml', 79.00, 'ដប', 'Sake'),
  (NULL, 'Nabeshima Tokubetsu Junmai-shu​ Yamada Nishiki 720ml', 59.00, 'ដប', 'Sake'),
  (NULL, 'Suigei Daito 2023 - 720ml', 405.00, 'ដប', 'Sake'),
  (NULL, 'Shiokawa Shuzo Nopa 720ml', 39.00, 'ដប', 'Sake'),
  (NULL, 'Shiokawa Shuzo  Cowboy Yamahai 720ml', 35.00, 'ដប', 'Sake'),
  (NULL, 'Shiokawa Shuzo Cowboy Yamaha Tender 720ml', 29.00, 'ដប', 'Sake'),
  (NULL, 'Shiokawa Shuzo Fisherman Sokujo Deep 720ml', 39.00, 'ដប', 'Sake'),
  (NULL, 'Shiokawa Shuzo Fisherman Sokujo 720ml', 35.00, 'ដប', 'Sake'),
  (NULL, 'Manrei Nomirinko Junmai Ginjo 720ml', 39.00, 'ដប', 'Sake'),
  (NULL, 'Manrei Junmai Daiginjo Akari 720ml', 49.00, 'ដប', 'Sake'),
  (NULL, 'Manrei Junmai Ginjo Nozomi 720ml', 39.00, 'ដប', 'Sake'),
  (NULL, 'Wakasa Junmai Ginjo 720ml', 49.00, 'ដប', 'Sake'),
  (NULL, 'Wakasa Junmai 720ml', 35.00, 'ដប', 'Sake'),
  (NULL, 'Momo Tsutau 720ml', 25.00, 'ដប', 'Sake'),
  (NULL, 'Hinoshita Musou Junmai Sparkling 720ml', 45.00, 'ដប', 'Sake'),
  (NULL, 'Hinoshita Musou Junmai 60 - 720ml', 39.00, 'ដប', 'Sake'),
  (NULL, 'Amabuki Kimoto Junmai Daiginjo Omachi 720ml', 49.00, 'ដប', 'Sake'),
  (NULL, 'Myokosan Akaisake Umakuchi 500ml', 29.00, 'ដប', 'Sake'),
  (NULL, 'Myokosan Junmai Daiginjo 720ml', 59.00, 'ដប', 'Sake'),
  (NULL, 'Myokosan 88 Kurabito Saibaimai Junmai Ginjo 720ml', 39.00, 'ដប', 'Sake'),
  (NULL, 'Myokosan Junmai Ginjo 720ml', 35.00, 'ដប', 'Sake'),
  (NULL, 'Myokosan Junmai 720ml', 35.00, 'ដប', 'Sake'),
  (NULL, 'Dassai 23 - 300ml', 79.00, 'ដប', 'Sake'),
  (NULL, 'Dassai 23 - 720ml', 169.00, 'ដប', 'Sake'),
  (NULL, 'Dassai 23 - 1800ml', 315.00, 'ដប', 'Sake'),
  (NULL, 'Dassai 39 - 300ml', 39.00, 'ដប', 'Sake'),
  (NULL, 'Dassai 39 - 720ml', 60.00, 'ដប', 'Sake'),
  (NULL, 'Dassai 39 - 1800ml', 179.00, 'ដប', 'Sake'),
  (NULL, 'Dassai 45 - 300ml', 29.00, 'ដប', 'Sake'),
  (NULL, 'Dassai 45 - 720ml', 45.00, 'ដប', 'Sake'),
  (NULL, 'Dassai 45 - 1800ml', 115.00, 'ដប', 'Sake'),
  (NULL, 'Dassai Beyond 720ml', 750.00, 'ដប', 'Sake'),
  (NULL, 'Frozen No Shell Scallop 250g', 20.00, 'កញ្ចប់', 'Shell'),
  (NULL, 'Azuma Nishin Yellow 500g (8pc)', 18.00, 'គីឡូ', 'Fish Roe'),
  (NULL, 'Azuma Nishin Red 500g (8pc)', 18.00, 'គីឡូ', 'Fish Roe'),
  (NULL, 'Orange Masago 250g', 12.00, 'កំប៉ុង', 'Fish Roe'),
  (NULL, 'Nakata Apple and Prune Liquor 500ml - Case', 145.00, 'កេស', 'Plum Wine & Liqueur'),
  (NULL, 'Nakata Peach and Plum Liquor 500ml (case)', 175.00, 'កេស', 'Plum Wine & Liqueur'),
  (NULL, 'Ogawa Shoten Purple Narabi 250g', 175.00, 'ប្រអប់', 'Uni - Fresh Urchin'),
  (NULL, 'Hokkigai Surl Clam 250g', 12.50, 'ឈុត', 'Shell'),
  (NULL, 'Temaki Sushi Roll', 55.00, 'ឈុត', 'Sushi Set'),
  (NULL, 'Sakai Russia Narabi (yellow) - 250g', 185.00, 'ប្រអប់', 'Uni - Fresh Urchin'),
  (NULL, 'Sapporo Premium Cans 500ml', 2.50, 'កំប៉ុង', 'Beer'),
  (NULL, 'Sapporo Premium Bottle 330ml', 2.00, 'ដប', 'Beer'),
  (NULL, 'Sapporo Premium Cans 500ml (case)', 55.00, 'កេស', 'Beer'),
  (NULL, 'Sapporo Premium Bottle 330ml (case)', 45.00, 'កេស', 'Beer'),
  (NULL, 'Classic Clear Soy Sauce', 6.50, 'ដប', 'Sauce & Oil'),
  (NULL, 'Golden Special Soy Sauce', 10.00, 'ដប', 'Sauce & Oil'),
  (NULL, 'Truffle Special Soy Sauce', 10.00, 'ដប', 'Sauce & Oil'),
  (NULL, 'Kanetomi Narabi Red - 250g', 175.00, 'ប្រអប់', 'Uni - Fresh Urchin'),
  (NULL, 'Kawamura SP Narabi - 250g', 185.00, 'ប្រអប់', 'Uni - Fresh Urchin'),
  (NULL, 'Nakata Kishu Plum wine Yuzu 180ml', 6.00, 'ដប', 'Plum Wine & Liqueur'),
  (NULL, 'Kimotokei Kodai 300ml', 25.00, 'ដប', 'Sake'),
  (NULL, 'Hinoshita Musou Sparkling 300ml', 25.00, 'ដប', 'Sake'),
  (NULL, 'Paradise Craft Beer Box set (6btl)', 55.00, 'ប្រអប់', 'Beer'),
  (NULL, 'Paradishu (Paradise Sake)', 85.00, 'ដប', 'Japanese Sake'),
  (NULL, 'Belle Green', 35.00, 'ប្រអប់', 'Health Supplement'),
  (NULL, 'Raw Vegetable Smoothie', 35.00, 'ប្រអប់', 'Health Supplement'),
  (NULL, 'MAGMA Enzyme', 35.00, 'ប្រអប់', 'Health Supplement'),
  (NULL, 'Yamachi Matcha (30g/pkt)', 15.00, 'កញ្ចប់', 'Beverage'),
  (NULL, 'Brown rice tea with matcha (150g/pkt)', 20.00, 'កញ្ចប់', 'Beverage'),
  (NULL, 'Hojicha Powder green tea (40g/pkt)', 15.00, 'កញ្ចប់', 'Beverage'),
  (NULL, 'Jack Daniel & Canadian Dry Ginger Highball 350ml', 4.00, 'កំប៉ុង', 'Plum Wine & Liqueur'),
  (NULL, 'Jack Daniel & Canadian Dry Ginger Highball 350ml (case)', 90.00, 'កេស', 'Plum Wine & Liqueur'),
  (NULL, 'Strawberry Matcha Unsweetened 30g', 25.00, 'កំប៉ុង', 'Beverage'),
  (NULL, 'Sakura Matcha Unsweetened 30g', 25.00, 'កំប៉ុង', 'Beverage'),
  (NULL, 'Lemon Matcha Unsweetened 30g', 25.00, 'កំប៉ុង', 'Beverage'),
  (NULL, 'Organically grown matcha "Fukusanari" 40g', 25.00, 'កញ្ចប់', 'Beverage'),
  (NULL, 'Organically grown Gyokuro 50g', 25.00, 'កញ្ចប់', 'Beverage'),
  (NULL, 'Hawthorn Concentrate (3x Dilution) 500ml Bottle', 25.00, 'ដប', 'Beverage'),
  (NULL, 'Tart Cherry Concentrate (3x diluted) 500ml bottle', 25.00, 'ដប', 'Beverage'),
  (NULL, 'Concentrated Sea Buckthorn Vinegar (3x diluted) 500ml', 25.00, 'ដប', 'Beverage'),
  (NULL, 'Yasumaru Red Japanese-style All-Purpose Dashi (30 packets)', 10.00, 'កញ្ចប់', 'Soup'),
  (NULL, 'Yasumaru Blue Fresh Dashi (30 packets)', 15.00, 'កញ្ចប់', 'Soup'),
  (NULL, 'Yasumaru Green Luxury Roasted Dashi (20 packets)', 10.00, 'កញ្ចប់', 'Soup'),
  (NULL, 'Kuromaru (Black garlic) 80g', 15.00, 'កញ្ចប់', 'Dried Items'),
  (NULL, 'Kuromaru (Black garlic) 120g', 25.00, 'កញ្ចប់', 'Dried Items'),
  (NULL, 'Suntory The Premium Malt''s 350ml', 3.50, 'កំប៉ុង', 'Beer'),
  (NULL, 'Curry Furikake 45g', 3.00, 'កញ្ចប់', 'Dried Items'),
  (NULL, 'Hakata Mentaiko Furikake 25g', 2.50, 'កញ្ចប់', 'Dried Items'),
  (NULL, 'Uni Furikake 35g', 4.00, 'កញ្ចប់', 'Dried Items'),
  (NULL, 'All Field Organic Malt Beer Box Set (6btl)', 55.00, 'ប្រអប់', 'Beer'),
  (NULL, 'YUTAS Premium Matcha', 6.00, 'កញ្ចប់', 'Beverage'),
  (NULL, 'YUTAS Water Matcha', 2.50, 'កញ្ចប់', 'Beverage'),
  (NULL, 'NIGHT RELAX -Chamomile & Roasted Sizouka Green Tea', 1.50, 'កញ្ចប់', 'Beverage'),
  (NULL, 'Rice flour Basque cheesecake', 4.50, 'កញ្ចប់', 'Dessert'),
  (NULL, 'Baked rice flour cheesecake', 4.50, 'កញ្ចប់', 'Dessert'),
  (NULL, 'Sake Cream Mochi Daifuku 30gx2', 2.00, 'ប្រអប់', 'Dessert'),
  (NULL, 'Baked Sweet Potato', 4.00, 'ប្រអប់', 'Dessert'),
  (NULL, 'Cream Daifuku (4pc,4 Flavor)', 6.00, 'ប្រអប់', 'Dessert'),
  (NULL, 'Steamed Hokkaido Octopus 1kg', 30.00, 'គីឡូ', 'Octopus'),
  (NULL, 'Hokkaido octopus legs (1kg/pkt)', 35.00, 'កញ្ចប់', 'Octopus'),
  (NULL, 'Steamed chunks (frozen) (1kg/pkt)', 35.00, 'កញ្ចប់', 'Octopus'),
  (NULL, 'Frozen Organic Natto Cup 40g×3', 5.50, 'កញ្ចប់', 'Processed Foods'),
  (NULL, 'Konjac Surume Black Pepper', 2.00, 'កញ្ចប់', 'Dessert'),
  (NULL, 'MOCHIKON with Chocolate', 8.50, 'កញ្ចប់', 'Dessert'),
  (NULL, 'Halal Mochikon Matcha', 5.00, 'កញ្ចប់', 'Dessert'),
  (NULL, 'Deep fried oysters 2L', 25.00, '​ប្រអប់', 'Processed Foods'),
  (NULL, 'Deep Fried Capelin (180g/pkt)', 10.00, 'កញ្ចប់', 'Processed Foods'),
  (NULL, 'Capelin with Roe 7L (5pc/pkt)', 10.00, '​កញ្ចប់', 'Fish'),
  (NULL, 'Boiled Snow Crab Claw Meat (1kg)', 75.00, 'កញ្ចប់', 'Shell'),
  (NULL, 'Boiled Snow Crab (whole)', 65.00, 'គីឡូ', 'Shell'),
  (NULL, 'Roasted Beef', 25.00, '​កញ្ចប់', 'Processed Foods'),
  (NULL, 'Milk Crepe Roll Matcha', 20.00, 'ប្រអប់', 'Dessert'),
  (NULL, 'Isuzu Matcha 40g', 25.00, 'កំប៉ុង', 'Beverage'),
  (NULL, 'Aorasahi Matcha 40g', 20.00, 'កំប៉ុង', 'Beverage'),
  (NULL, 'Soy-Braised Horese Tendon-Kumamoto Stayle', 4.50, 'កញ្ចប់', 'Processed Foods'),
  (NULL, 'SAKARI NO.22 MATCHA', 29.00, 'ដប', 'Sake'),
  (NULL, 'Frozen Uni 100g (Limited)', 27.00, 'ប្រអប់', 'Frozen Premium'),
  (NULL, 'Fresh Wagyu A5', 210.00, 'គីឡូ', 'Meat & Poultry'),
  (NULL, 'Asahi Super Dry (Can)​​ - 330ml', 2.00, 'កំប៉ុង', 'Beer'),
  (NULL, 'Asahi Super Dry 330ml (Case)', 45.00, 'កេស', 'Beer'),
  (NULL, 'Frozen Hotate', 14.00, '100g', 'Shell'),
  (NULL, 'Frozen Matsusaka Beef A5 Sirloin (Limited)', 190.00, 'គីឡូ', 'Meat & Poultry'),
  (NULL, 'Fresh Salmon Fillet 1kg (Local)', 40.00, '1kg', 'Fish'),
  (NULL, 'Sashimi Set B', 28.50, 'ឈុត', 'Sashimi Set'),
  (NULL, 'Sashimi Set C', 35.50, 'ឈុត', 'Sashimi Set'),
  (NULL, 'Fresh Uni ft Sashimi', 25.00, 'ឈុត', 'Sashimi Set'),
  (NULL, 'Sashimi Set E', 30.00, 'ឈុត', 'Sashimi Set'),
  (NULL, 'Sashimi Set F', 30.00, 'ឈុត', 'Sashimi Set'),
  (NULL, 'Ukon no Chikara', 3.50, 'ដប', 'Soft Drink'),
  (NULL, 'Ukon no Chikara SUPER', 6.00, 'ដប​', 'Soft Drink'),
  (NULL, 'Azuma Yellow Nishin 1pc (limited)', 5.50, 'ដុំ', 'Fish Roe'),
  (NULL, 'Frozen Uni 100g ft Sashimi', 35.00, 'ឈុត', 'Sashimi Set'),
  (NULL, 'Snow Crab Leg Portion', 38.50, 'កញ្ចប់', 'Shell'),
  (NULL, 'Rice Flour and Tofu Chocolate Brownie', 4.50, 'កញ្ចប់', 'Dessert'),
  (NULL, 'Sashimi Set A', 45.00, 'ឈុត', 'Sashimi Set'),
  (NULL, 'Frozen Hotate 1kg', 140.00, '1kg', 'Shell'),
  (NULL, 'Frozen Hotate 250g', 35.00, 'កញ្ចប់', 'Shell'),
  (NULL, 'Paradise Craft Beer (Black)', 9.17, 'ដប', 'Beer'),
  (NULL, 'Paradise Craft Beer (Pink)', 9.17, 'ដប', 'Beer'),
  (NULL, 'Paradise Craft Beer (Yellow)', 9.17, 'ដប', 'Beer'),
  (NULL, 'Paradise Craft Beer (White)', 9.17, 'ដប', 'Beer'),
  (NULL, 'Paradise Craft Beer (Orange)', 9.17, 'ដប', 'Beer'),
  (NULL, 'Paradise Craft Beer (Green)', 9.17, 'ដប', 'Beer'),
  (NULL, 'Paradise Beer (btl)', 9.17, 'ដប', 'Beer'),
  (NULL, 'Ukon No Chikara - Orange Flavor', 3.50, 'ដប', 'Soft Drink'),
  (NULL, 'Premium Snow Crab Leg Portion', 40.00, 'កញ្ចប់', 'Shell')
) as v(sku, name, price, unit, category_name)
join cat_map on cat_map.name = v.category_name;
